# This workflow will build a Java project with Gradle then perform an automated release
# For more information see:
#  https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#  https://github.com/marketplace/actions/action-for-semantic-release

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build-directory
          path: build
      - uses: codecov/codecov-action@v1
        with:
          files: service/build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true
